import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {Header} from "./components/Header";


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Potafolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='content'>
       <header className='headerLayout'>
        <Header button1="Home" button2="Services" button3="About Us"/>
       </header>
         {children}
      </body>
    </html>
  )
}
