import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {Header} from "./components/Header";
import {Footer} from "./components/Footer"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Potafolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='content'>
       <header className='headerLayout'>
        <Header button1="Services" button2='Plataform'/>
       </header>
         {children}
       <Footer title='Footer'/>
      </body>
    </html>
  )
}
